name: Dependency Submission

on:
  push:
    branches:
      - main
    paths:
      - "gradle/libs.versions.toml"
      - "**.gradle.kts"
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 1'

permissions:
  id-token: write
  contents: write

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Get Vault secrets
        uses: hashicorp/vault-action@v2.7.5
        with:
          url: ${{ secrets.VAULT_ADDRESS_LIVE }}
          method: jwt
          path: jwt_github
          role: pdh-distribution-analytics
          jwtGithubAudience: ${{ secrets.VAULT_JWT_GITHUB_AUDIENCE }}
          exportToken: "true"
          secrets: |
            pdh-distribution-analytics/data/global/config github-packages-token | GITHUB_PACKAGES_READ_TOKEN;
      - name: Setup JDK 17 corretto
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
          cache: gradle
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v3
        env:
          GITHUB_PACKAGES_READ_TOKEN: ${{ secrets.PACKAGES_READ_TOKEN }}
